apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-feature-deployment
  namespace: kubernetes-cluster-gaganjotsingh02
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gaganshera/i-gaganjotsingh02-feature:latest
          ports:
            - name: http
              containerPort: 3010
              protocol: TCP
          envFrom:
          - configMapRef:
              name: app-settings
          # - secretRef:
          #     name: secret-info
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-feature
  namespace: kubernetes-cluster-gaganjotsingh02
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-settings"
  namespace: kubernetes-cluster-gaganjotsingh02
  labels:
    app: "app-settings"
data:
  API_URL: "http://google.com"
  ENVIRONMENT: "dev"
  LANGUAGE: "English"