apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: gagan-k8s
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gaganshera/nagp-2021-node-devops-app
          ports:
            - name: http
              containerPort: 3010
              protocol: TCP
          # envFrom:
          # - configMapRef:
          #     name: app-settings
          # - secretRef:
          #     name: secret-info
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "node-app-lb"
  namespace: "gagan-k8s"
  labels:
    app: "node-app-lb"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3010
  selector:
    app: "node-app"
  type: "LoadBalancer"
  #http
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   namespace: gagan-k8s
#   name: node-app-deployment-autoscale
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: node-app-deployment
#   minReplicas: 1
#   maxReplicas: 4
#   targetCPUUtilizationPercentage: 10